{
	"version": 1739530035,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/bullet-sheet0.png",
		"images/turret-sheet0.png",
		"images/hearts-sheet0.png",
		"images/hearts-sheet1.png",
		"images/bg-sheet0.png",
		"images/particles.png",
		"images/banana__2d_art-sheet0.png",
		"images/sprite-sheet0.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/pop.m4a",
		"media/pop.ogg",
		"media/valentines confusion - bgm.m4a",
		"media/valentines confusion - bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}